In [3]:
import numpy as np

In [11]:
np.random.rand(3,3)

array([[ 0.33420521, -0.57732458, -1.03886057],
       [ 1.09752088, -0.7992277 , -0.34283658],
       [-1.10223085, -0.68757926, -1.802982  ]])

In [13]:
np.random.randint(50,100,5)
# low (inclusive) to high (exclusive).

array([73, 85, 55, 96, 73])

In [14]:
arr = np.arange(15)
ran_arr = np.random.randint(0,100,15)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
ran_arr

array([81, 55, 64, 28, 26, 41, 99, 17, 45, 14, 43, 99, 48, 23, 58])

In [17]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr.reshape(3,5).shape

(3, 5)

In [20]:
arr.dtype

dtype('int32')

In [26]:
np.linspace(0,20,10).reshape(5,2)

array([[ 0.        ,  2.22222222],
       [ 4.44444444,  6.66666667],
       [ 8.88888889, 11.11111111],
       [13.33333333, 15.55555556],
       [17.77777778, 20.        ]])

In [30]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
ran_arr.max()

99

In [34]:
ran_arr.argmax()

6

In [35]:
ran_arr.min()

14

In [36]:
ran_arr.argmin()

9