In [95]:
import numpy as np

In [96]:
arr = np.arange(0,11)

In [97]:
arr[2]

2

In [98]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [99]:
arr[-1]

10

In [100]:
arr[0:3]

array([0, 1, 2])

In [101]:
arr[0:9:3]

array([0, 3, 6])

In [102]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [103]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
# Broadcasting

arr[2:5] = 100
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [105]:
slice_of_arr = arr[0:5]
slice_of_arr

array([  0,   1, 100, 100, 100])

In [106]:
slice_of_arr[:] = 33
slice_of_arr

array([33, 33, 33, 33, 33])

In [107]:
arr

#slice is a poiter to array
# and could actually change the original array

array([33, 33, 33, 33, 33,  5,  6,  7,  8,  9, 10])

In [108]:
arr_copy = arr.copy()

In [109]:
arr_copy[:] = 899
arr_copy

array([899, 899, 899, 899, 899, 899, 899, 899, 899, 899, 899])

In [110]:
arr

array([33, 33, 33, 33, 33,  5,  6,  7,  8,  9, 10])

In [111]:
# The general format is arr_2d[row][col]
# or arr_2d[row,col]
# I recommend usually using the comma notation for clarity.

mat = np.arange(25).reshape(5,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
mat[0]


array([0, 1, 2, 3, 4])

In [113]:
mat[-1]

array([20, 21, 22, 23, 24])

In [114]:
mat[1,2]

7

In [115]:
mat[0,2]

2

In [116]:
mat[0][2]

2

In [117]:
mat[3]

array([15, 16, 17, 18, 19])

In [118]:
mat[:,3:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [119]:
mat[1:4,3:]

# [include:exclude, include:exclude]
# Starts from 0

array([[ 8,  9],
       [13, 14],
       [18, 19]])

In [120]:
mat[(1,2,3,4),(0,1,2,3)]

array([ 5, 11, 17, 23])

In [121]:
mask_0 = np.array([1,0,0,1,1], dtype = bool)
mat[mask_0,2]

array([ 2, 17, 22])

In [122]:
mat >12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [123]:
bool_mat = mat > 12
bool_mat

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [124]:
mat[bool_mat]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [125]:
mat[mat>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])